# .pages.yml
media:
  output: static/img
  public_url: /img

content:
  - label: Documentation
    path: docs
    type: collection
    extension: md
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Content
        type: rich-text